export const users = [
    {
        user_id: "123",
        username: "sai",
        domain: "/sai",
        created_at: new Date(),
        confirmed: true,
        viewers: 0,
        subscription: 0,
        vods: 0,
        twofactor: false,
        email: "",
        phone: null,
        photo: null,
        description: null,
        channel_trailer: null,
        banner: null,
        tags: null
    },
    {
        user_id: "124",
        username: "sumith",
        domain: "/sumith",
        created_at: new Date(),
        confirmed: true,
        viewers: 0,
        subscription: 0,
        vods: 0,
        twofactor: false,
        email: "",
        phone: null,
        photo: null,
        description: null,
        channel_trailer: null,
        banner: null,
        tags: null
    },
    {
        user_id: "125",
        username: "suresh",
        domain: "/suresh",
        created_at: new Date(),
        confirmed: true,
        viewers: 0,
        subscription: 0,
        vods: 0,
        twofactor: false,
        email: "",
        phone: null,
        photo: null,
        description: null,
        channel_trailer: null,
        banner: null,
        tags: null
    }
]